import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

import { verifyAccessToken } from "@/lib/jwt";

type LegacyUserCookie = {
  role?: string;
};

function parseLegacyUserCookie(cookie?: string): LegacyUserCookie | null {
  if (!cookie) {
    return null;
  }

  try {
    return JSON.parse(cookie);
  } catch {
    return null;
  }
}

/**
 * Check if a token looks valid (has JWT structure: 3 parts separated by dots)
 * This is a lightweight check before attempting full verification
 * Also accepts mock tokens when in mock mode
 */
function isTokenStructureValid(token: string): boolean {
  // In mock mode, accept mock tokens
  if (process.env.USE_MOCK_DATA === "true" && token.startsWith("mock_jwt_")) {
    return true;
  }
  
  const parts = token.split(".");
  return parts.length === 3 && parts.every((part) => part.length > 0);
}

/**
 * Try to extract role from token payload without full verification
 * This helps handle PHP-generated tokens that may not verify with Next.js JWT library
 */
function tryExtractRoleFromToken(token: string): string | null {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return null;
    
    // Decode the payload (second part)
    const payload = JSON.parse(
      Buffer.from(parts[1].replace(/-/g, "+").replace(/_/g, "/"), "base64").toString()
    );
    
    // Check if token is expired
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
      return null;
    }
    
    return payload.role?.toUpperCase() ?? null;
  } catch {
    return null;
  }
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  const accessToken = request.cookies.get("earniq_access_token")?.value;
  const legacyToken = request.cookies.get("sparkio_token")?.value;
  const token = accessToken || legacyToken;
  const legacyUser = parseLegacyUserCookie(request.cookies.get("sparkio_user")?.value);
  const earniqUser = parseLegacyUserCookie(request.cookies.get("earniq_user")?.value);

  const isAuthRoute = pathname.startsWith("/login") || pathname.startsWith("/register");
  const isMemberRoute = pathname.startsWith("/member");
  const isAdminRoute = pathname.startsWith("/admin");

  // Determine if user is authenticated and their role
  let isAuthenticated = false;
  let userRole: string | null = null;

  if (token && isTokenStructureValid(token)) {
    // Handle mock tokens when in mock mode
    if (process.env.USE_MOCK_DATA === "true" && token.startsWith("mock_jwt_")) {
      // Extract user info from mock token or user cookie
      const userFromCookie = earniqUser || legacyUser;
      if (userFromCookie?.role) {
        userRole = userFromCookie.role.toUpperCase();
        isAuthenticated = true;
      } else {
        // Try to extract from token format: mock_jwt_userId_timestamp
        // For now, default to MEMBER if we can't determine from cookie
        userRole = "MEMBER";
        isAuthenticated = true;
      }
    } else {
      // Try Next.js JWT verification first (for tokens generated by Next.js)
      if (accessToken) {
        try {
          const payload = verifyAccessToken(accessToken);
          userRole = payload.role?.toUpperCase() ?? null;
          isAuthenticated = true;
        } catch {
          // Token might be PHP-generated, try extracting role directly
          const extractedRole = tryExtractRoleFromToken(accessToken);
          if (extractedRole) {
            userRole = extractedRole;
            isAuthenticated = true;
          }
        }
      } else if (legacyToken) {
        // Try extracting role from legacy token
        const extractedRole = tryExtractRoleFromToken(legacyToken);
        if (extractedRole) {
          userRole = extractedRole;
          isAuthenticated = true;
        }
      }
    }
  }

  // Fall back to user cookie if token verification failed
  // In mock mode, if we have a token and user cookie, consider authenticated
  if (!isAuthenticated) {
    const userFromCookie = earniqUser || legacyUser;
    if (userFromCookie?.role) {
      userRole = userFromCookie.role.toUpperCase();
      // Only consider authenticated if we have a token (even if we couldn't verify it)
      // In mock mode, accept mock tokens
      if (token) {
        if (process.env.USE_MOCK_DATA === "true" && token.startsWith("mock_jwt_")) {
          isAuthenticated = true;
        } else {
          isAuthenticated = true; // Token exists, even if we couldn't verify it
        }
      }
    }
  }

  // Redirect unauthenticated users away from protected routes
  if ((isMemberRoute || isAdminRoute) && !isAuthenticated) {
    const redirectUrl = request.nextUrl.clone();
    redirectUrl.pathname = "/login";
    redirectUrl.searchParams.set("redirect", `${pathname}${request.nextUrl.search}`);
    return NextResponse.redirect(redirectUrl);
  }

  // Redirect authenticated users away from auth pages
  if (isAuthenticated && isAuthRoute) {
    const redirectUrl = request.nextUrl.clone();
    redirectUrl.pathname = userRole === "ADMIN" ? "/admin/dashboard" : "/member/dashboard";
    redirectUrl.search = "";
    return NextResponse.redirect(redirectUrl);
  }

  // Redirect non-admin users away from admin routes
  if (isAuthenticated && isAdminRoute && userRole !== "ADMIN") {
    const redirectUrl = request.nextUrl.clone();
    redirectUrl.pathname = "/member/dashboard";
    redirectUrl.search = "";
    return NextResponse.redirect(redirectUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/member/:path*", "/admin/:path*", "/dashboard/:path*", "/login", "/register"],
};

